#!/usr/bin/env python3
"""Plan-driven Tianyi palletizing replay in Isaac Gym.

This runner consumes the PCT online packing case JSON files generated by
``move.online_palletizing``.  It creates the Tianyi/XHand robot, a source table,
a 1m x 1m pallet, and one box per online item.  The boxes are carried
kinematically along robot root motion and released at the PCT placements.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import imageio.v2 as imageio
import numpy as np

try:
    from isaacgym import gymapi  # type: ignore
    from isaacgym import gymtorch  # type: ignore
    import torch
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Isaac Gym Python package is not importable. Use run_move_bpp_env.sh.") from exc

MOVE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = MOVE_ROOT.parent
sys.path.insert(0, str(REPO_ROOT))

from move.planning import PALLET_SURFACE_Z, PALLET_THICKNESS, TABLE_POSE, TABLE_SIZE, Pose, pallet_center_near_table  # noqa: E402
from move.tasks.move_test1 import (  # noqa: E402
    BOX_MASS,
    _load_hold_targets,
    _make_transform,
    _set_color,
    _set_shape_friction,
    create_sim,
    load_robot_asset,
    sample_root_trajectory,
)

PALETTE = (
    (0.88, 0.20, 0.16), (0.20, 0.48, 0.88), (0.18, 0.68, 0.36), (0.95, 0.73, 0.16),
    (0.55, 0.32, 0.78), (0.90, 0.46, 0.12), (0.10, 0.70, 0.68), (0.24, 0.30, 0.36),
)
SOURCE_X = TABLE_POSE[0] - 0.10
SOURCE_Y = TABLE_POSE[1]
ROBOT_STAND_OFF = 0.72
SAFE_MARGIN = 1.15
LIFT_CLEARANCE = 0.28
PLACE_CLEARANCE = 0.08
HOLD_FRAMES = 18
FPS = 30


def _smoothstep(alpha: float) -> float:
    alpha = max(0.0, min(1.0, float(alpha)))
    return alpha * alpha * (3.0 - 2.0 * alpha)


def _lerp(a: tuple[float, float, float], b: tuple[float, float, float], alpha: float) -> tuple[float, float, float]:
    return tuple(a[i] * (1.0 - alpha) + b[i] * alpha for i in range(3))  # type: ignore[return-value]


def _box_world_center(pallet_center: tuple[float, float, float], placement: dict) -> tuple[float, float, float]:
    mn = placement["min_corner_m"]
    mx = placement["max_corner_m"]
    return (
        pallet_center[0] - 0.5 + 0.5 * (mn[0] + mx[0]),
        pallet_center[1] - 0.5 + 0.5 * (mn[1] + mx[1]),
        pallet_center[2] + 0.5 * (mn[2] + mx[2]),
    )


def _source_center(size: tuple[float, float, float]) -> tuple[float, float, float]:
    return (SOURCE_X, SOURCE_Y, TABLE_POSE[2] + TABLE_SIZE[2] * 0.5 + size[2] * 0.5)


def _route_for_target(target: tuple[float, float, float], pallet_center: tuple[float, float, float]) -> list[Pose]:
    final_x = pallet_center[0] - 0.5 - ROBOT_STAND_OFF
    final_y = target[1]
    yaw = math.atan2(target[1] - final_y, target[0] - final_x)
    safe = Pose(pallet_center[0] - 0.5 - SAFE_MARGIN, pallet_center[1] - 0.5 - SAFE_MARGIN, 0.0, 0.0)
    start = Pose(0.0, 0.0, 0.0, 0.0)
    retreat = Pose(-0.90, 0.0, 0.0, 0.0)
    axis1 = Pose(retreat.x, safe.y, 0.0, math.atan2(safe.y - retreat.y, safe.x - retreat.x))
    axis2 = Pose(safe.x, safe.y, 0.0, 0.0)
    approach_axis = Pose(final_x, safe.y, 0.0, math.atan2(final_y - safe.y, final_x - safe.x))
    preplace = Pose(final_x, final_y, 0.0, yaw)
    return [start, retreat, axis1, axis2, approach_axis, preplace]


def _pose_frames(waypoints: list[Pose]) -> list[Pose]:
    frames: list[Pose] = []
    for start, goal in zip(waypoints, waypoints[1:]):
        frames.extend(sample_root_trajectory(start, goal, linear_speed=0.55, yaw_speed=0.8, lift_speed=0.3))
    frames.extend([waypoints[-1]] * HOLD_FRAMES)
    return frames


def _set_pose_in_root_state(root_states: torch.Tensor, actor_index: int, pos: tuple[float, float, float], yaw: float = 0.0) -> None:
    state = root_states[actor_index]
    state[0], state[1], state[2] = pos
    half = yaw * 0.5
    state[3] = 0.0
    state[4] = 0.0
    state[5] = math.sin(half)
    state[6] = math.cos(half)
    state[7:13] = 0.0


def _apply_root_states(gym, sim, root_states: torch.Tensor, indices: list[int]) -> None:
    tensor = torch.tensor(indices, dtype=torch.int32)
    gym.set_actor_root_state_tensor_indexed(sim, gymtorch.unwrap_tensor(root_states), gymtorch.unwrap_tensor(tensor), len(indices))


def _camera_frame(gym, sim, env, cam) -> np.ndarray:
    gym.step_graphics(sim)
    gym.render_all_camera_sensors(sim)
    image = gym.get_camera_image(sim, env, cam, gymapi.IMAGE_COLOR)
    arr = np.asarray(image, dtype=np.uint8)
    if arr.ndim == 2 and arr.shape[1] % 4 == 0:
        arr = arr.reshape(arr.shape[0], arr.shape[1] // 4, 4)
    elif arr.ndim != 3 or arr.shape[2] < 3:
        raise RuntimeError(f"Unexpected camera image shape: {arr.shape}")
    return arr[:, :, :3].copy()


def _write_camera_frame(gym, sim, env, cam, path: Path) -> None:
    gym.step_graphics(sim)
    gym.render_all_camera_sensors(sim)
    gym.write_camera_image_to_file(sim, env, cam, gymapi.IMAGE_COLOR, str(path))


def main() -> None:
    parser = argparse.ArgumentParser(description="Run a PCT case as a Tianyi palletizing replay.")
    parser.add_argument("--case", type=Path, required=True)
    parser.add_argument("--video", type=Path, default=None)
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--max-items", type=int, default=0)
    parser.add_argument("--record-every", type=int, default=4)
    parser.add_argument("--camera-width", type=int, default=640)
    parser.add_argument("--camera-height", type=int, default=360)
    args = parser.parse_args()

    case = json.loads(args.case.read_text())
    placements = case["placements"]
    if args.max_items > 0:
        placements = placements[: args.max_items]
    pallet_center = pallet_center_near_table()

    gym = gymapi.acquire_gym()
    sim = create_sim(gym)
    if sim is None:
        raise RuntimeError("Failed to create Isaac Gym simulation")
    plane = gymapi.PlaneParams()
    plane.normal = gymapi.Vec3(0, 0, 1)
    gym.add_ground(sim, plane)

    robot_asset = load_robot_asset(gym, sim)
    fixed_opts = gymapi.AssetOptions()
    fixed_opts.fix_base_link = True
    table_asset = gym.create_box(sim, TABLE_SIZE[0], TABLE_SIZE[1], TABLE_SIZE[2], fixed_opts)
    pallet_asset = gym.create_box(sim, 1.0, 1.0, PALLET_THICKNESS, fixed_opts)

    box_assets = []
    for p in placements:
        sx, sy, sz = [float(v) for v in p["placed_size_m"]]
        opts = gymapi.AssetOptions()
        opts.density = BOX_MASS / max(sx * sy * sz, 1e-6)
        box_assets.append(gym.create_box(sim, sx, sy, sz, opts))

    env = gym.create_env(sim, gymapi.Vec3(-1.5, -1.5, 0.0), gymapi.Vec3(6.5, 6.5, 2.5), 1)
    robot = gym.create_actor(env, robot_asset, _make_transform(0.0, 0.0, 0.0), "tianyi_palletizer", 0, 1)
    table = gym.create_actor(env, table_asset, _make_transform(*TABLE_POSE), "source_table", 0, 0)
    pallet = gym.create_actor(env, pallet_asset, _make_transform(pallet_center[0], pallet_center[1], PALLET_SURFACE_Z - PALLET_THICKNESS * 0.5), "pallet", 0, 0)
    boxes = []
    for i, (asset, p) in enumerate(zip(box_assets, placements)):
        size = tuple(float(v) for v in p["placed_size_m"])
        boxes.append(gym.create_actor(env, asset, _make_transform(*_source_center(size)), f"item_{i:02d}", 0, 0))

    _set_color(gym, env, table, (0.95, 0.95, 0.92))
    _set_color(gym, env, pallet, (0.15, 0.55, 0.45))
    for i, box in enumerate(boxes):
        _set_color(gym, env, box, PALETTE[i % len(PALETTE)])
    _set_shape_friction(gym, env, robot, 2.0)
    _set_shape_friction(gym, env, table, 1.2)
    _set_shape_friction(gym, env, pallet, 1.4)
    for box in boxes:
        _set_shape_friction(gym, env, box, 2.0)

    dof_names = list(gym.get_asset_dof_names(robot_asset))
    props = gym.get_actor_dof_properties(env, robot)
    props["driveMode"].fill(gymapi.DOF_MODE_POS)
    for idx, name in enumerate(dof_names):
        props["stiffness"][idx] = 120.0 if name.startswith("xhand_") else 360.0
        props["damping"][idx] = 12.0 if name.startswith("xhand_") else 36.0
    gym.set_actor_dof_properties(env, robot, props)
    lower = torch.tensor(props["lower"], dtype=torch.float32)
    upper = torch.tensor(props["upper"], dtype=torch.float32)
    hold_targets = _load_hold_targets(dof_names, lower, upper)
    dof_state = gym.get_actor_dof_states(env, robot, gymapi.STATE_ALL)
    dof_state["pos"] = hold_targets.numpy()
    dof_state["vel"].fill(0.0)
    gym.set_actor_dof_states(env, robot, dof_state, gymapi.STATE_ALL)
    gym.set_actor_dof_position_targets(env, robot, hold_targets.numpy())

    cam = None
    if args.video is not None:
        cam_props = gymapi.CameraProperties()
        cam_props.width = args.camera_width
        cam_props.height = args.camera_height
        cam = gym.create_camera_sensor(env, cam_props)
        gym.set_camera_location(cam, env, gymapi.Vec3(pallet_center[0] + 1.9, pallet_center[1] - 2.3, 1.65), gymapi.Vec3(pallet_center[0], pallet_center[1], 0.55))

    gym.prepare_sim(sim)
    root_states = gymtorch.wrap_tensor(gym.acquire_actor_root_state_tensor(sim))
    robot_index = gym.get_actor_index(env, robot, gymapi.DOMAIN_SIM)
    box_indices = [gym.get_actor_index(env, box, gymapi.DOMAIN_SIM) for box in boxes]

    video_frames = []
    frame_files = []
    frame_dir = None
    if args.video is not None:
        frame_dir = args.video.with_suffix("")
        frame_dir.mkdir(parents=True, exist_ok=True)
    frame = 0
    print(f"robot_palletizing case={case['case_id']} items={len(placements)} video={args.video}")
    try:
        for item_idx, p in enumerate(placements):
            size = tuple(float(v) for v in p["placed_size_m"])
            source = _source_center(size)
            target = _box_world_center(pallet_center, p)
            lifted_source = (source[0], source[1], max(source[2] + LIFT_CLEARANCE, target[2] + PLACE_CLEARANCE))
            lifted_target = (target[0], target[1], max(source[2] + LIFT_CLEARANCE, target[2] + PLACE_CLEARANCE))
            route = _pose_frames(_route_for_target(target, pallet_center))
            box_path = []
            for i, _pose in enumerate(route):
                a = _smoothstep(i / max(1, len(route) - 1))
                if a < 0.20:
                    b = a / 0.20
                    center = _lerp(source, lifted_source, _smoothstep(b))
                elif a < 0.82:
                    b = (a - 0.20) / 0.62
                    center = _lerp(lifted_source, lifted_target, _smoothstep(b))
                else:
                    b = (a - 0.82) / 0.18
                    center = _lerp(lifted_target, target, _smoothstep(b))
                box_path.append(center)

            for pose, center in zip(route, box_path):
                gym.refresh_actor_root_state_tensor(sim)
                _set_pose_in_root_state(root_states, robot_index, (pose.x, pose.y, pose.z), pose.yaw)
                _set_pose_in_root_state(root_states, box_indices[item_idx], center, 0.0)
                _apply_root_states(gym, sim, root_states, [robot_index, box_indices[item_idx]])
                gym.set_actor_dof_position_targets(env, robot, hold_targets.numpy())
                gym.simulate(sim)
                gym.fetch_results(sim, True)
                if cam is not None and frame % max(1, args.record_every) == 0:
                    frame_path = frame_dir / f"frame_{len(frame_files):05d}.png"
                    _write_camera_frame(gym, sim, env, cam, frame_path)
                    frame_files.append(frame_path)
                frame += 1
            gym.refresh_actor_root_state_tensor(sim)
            _set_pose_in_root_state(root_states, box_indices[item_idx], target, 0.0)
            _apply_root_states(gym, sim, root_states, [box_indices[item_idx]])
            print(f"placed item={item_idx:02d} size={size} target=({target[0]:.3f},{target[1]:.3f},{target[2]:.3f}) util={p['utilization']:.3f}")

        for _ in range(45):
            gym.simulate(sim)
            gym.fetch_results(sim, True)
            if cam is not None and frame % max(1, args.record_every) == 0:
                frame_path = frame_dir / f"frame_{len(frame_files):05d}.png"
                _write_camera_frame(gym, sim, env, cam, frame_path)
                frame_files.append(frame_path)
            frame += 1
    finally:
        if args.video is not None and frame_files:
            args.video.parent.mkdir(parents=True, exist_ok=True)
            frames = [imageio.imread(path)[:, :, :3] for path in frame_files]
            imageio.mimsave(args.video, frames, fps=FPS)
            print(f"wrote_video={args.video} frames={len(frame_files)} frame_dir={frame_dir}")
        gym.destroy_sim(sim)


if __name__ == "__main__":
    main()
